branch-defaults:
  main:
    environment: jv-prophecy-prod
  staging:
    environment: jv-prophecy-staging
    
deploy:
  artifact: deploy.zip

global:
  application_name: jv-prophecy-manager
  default_ec2_keyname: jv-prophecy-key
  default_platform: PHP 8.2 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application

